import 'dotenv/config';
import { PrismaClient } from '../generated/prisma/client.js';
import { PrismaPg } from '@prisma/adapter-pg';
import { Pool } from 'pg';

const pool = new Pool({
  connectionString: process.env.DATABASE_URL,
});

const adapter = new PrismaPg(pool);
const prisma = new PrismaClient({ adapter });

const sampleCars = [
  {
    brand: 'Toyota',
    model: 'Corolla',
    year: 2022,
    price: 28500000,
    mileage: 15000,
    fuelType: 'nafta',
    transmission: 'automatica',
    status: 'available',
    featured: true,
    description: 'Toyota Corolla XEi en excelente estado. Único dueño, todos los services oficiales. Kit de mantenimiento al día. Neumáticos nuevos. Ideal para uso familiar.',
    features: [
      'Aire acondicionado digital',
      'Dirección asistida eléctrica',
      'Cierre centralizado',
      'Alarma con levantavidrios',
      'Airbags frontales y laterales',
      'Sensor de estacionamiento trasero',
      'Cámara de reversa',
      'Bluetooth',
      'Android Auto y Apple CarPlay',
      'Llave inteligente',
      'Sensor de lluvia',
    ],
    specs: {
      engine: '2.0 16v Dynamic Force 169cv',
      steering: 'electric',
      color: 'Blanco Perlado',
      doors: 4,
      wheels: 'Aleación 17 pulgadas',
      wheelSize: '225/45 R17',
      audioSystem: 'Pantalla táctil 8" + 6 parlantes + Android Auto/Apple CarPlay',
      headlights: 'led',
      sensors: ['parking', 'reverse', 'rain'],
      securityFeatures: [
        'airbags',
        'abs',
        'esp',
        'traction-control',
        'brake-assist',
        'hill-holder',
        'isofix',
      ],
      comfortFeatures: [
        'cruise-control',
        'leather-seats',
        'electric-mirrors',
        'electric-windows',
        'climate-control',
        'dual-zone-climate',
        'start-stop',
      ],
    },
  },
  {
    brand: 'Volkswagen',
    model: 'Golf',
    year: 2021,
    price: 26500000,
    mileage: 28000,
    fuelType: 'nafta',
    transmission: 'automatica',
    status: 'available',
    featured: true,
    description: 'VW Golf Highline DSG. El mejor hatchback del segmento. Interior impecable, tapizado de cuero. Muy buen estado mecánico. Lista para transferir.',
    features: [
      'Climatronic bizona',
      'Sistema Start-Stop',
      'Modos de conducción',
      'Faros LED adaptativos',
      'Sensor de fatiga',
      'Asistente de arranque en pendiente',
      'Volante multifunción',
      'Bluetooth',
      'Sensores de estacionamiento delanteros y traseros',
      'Cámara de retroceso',
      'Quemacocos',
    ],
    specs: {
      engine: '1.4 TSI 150cv Turbo',
      steering: 'electric',
      color: 'Gris Platino',
      doors: 5,
      wheels: 'Aleación 18 pulgadas',
      wheelSize: '225/40 R18',
      audioSystem: 'Pantalla Composition Media 8" + 8 parlantes',
      headlights: 'full-led',
      sensors: ['parking', 'reverse'],
      securityFeatures: [
        'airbags',
        'abs',
        'esp',
        'traction-control',
        'brake-assist',
        'hill-holder',
      ],
      comfortFeatures: [
        'cruise-control',
        'sunroof',
        'leather-seats',
        'heated-seats',
        'electric-mirrors',
        'electric-windows',
        'climate-control',
        'dual-zone-climate',
        'start-stop',
      ],
    },
  },
  {
    brand: 'Honda',
    model: 'Civic',
    year: 2023,
    price: 32500000,
    mileage: 8000,
    fuelType: 'nafta',
    transmission: 'cvt',
    status: 'available',
    featured: true,
    description: 'Honda Civic Touring 0km prácticamente. Todas las revisiones al día. Garantía de fábrica vigente. Oportunidad única.',
    features: [
      'Sistema Honda Sensing',
      'Asientos de cuero eléctricos',
      'Volante calefaccionado',
      'Cargador inalámbrico',
      'Pantalla táctil 9"',
      'Sistema de audio Premium 12 parlantes',
      'Techo solar eléctrico',
      'Sensores de punto ciego',
      'Alerta de tráfico cruzado',
      'Asistente de mantenimiento de carril',
    ],
    specs: {
      engine: '2.0 16v i-VTEC 154cv',
      steering: 'electric',
      color: 'Azul Obsidiana',
      doors: 4,
      wheels: 'Aleación 18 pulgadas',
      wheelSize: '235/40 R18',
      audioSystem: 'Sistema Premium Bose 12 parlantes + Subwoofer',
      headlights: 'full-led',
      sensors: ['parking', 'reverse', 'blindspot', 'rain'],
      securityFeatures: [
        'airbags',
        'abs',
        'esp',
        'traction-control',
        'brake-assist',
        'hill-holder',
        'isofix',
      ],
      comfortFeatures: [
        'cruise-control',
        'sunroof',
        'leather-seats',
        'heated-seats',
        'electric-mirrors',
        'electric-windows',
        'climate-control',
        'dual-zone-climate',
        'start-stop',
        'parking-brake-electric',
      ],
    },
  },
  {
    brand: 'Ford',
    model: 'Focus',
    year: 2020,
    price: 19800000,
    mileage: 55000,
    fuelType: 'nafta',
    transmission: 'manual',
    status: 'available',
    featured: false,
    description: 'Ford Focus SE Plus. Excelente estado, motor impecable. Ideal para quien busca un auto confiable y económico.',
    features: [
      'Aire acondicionado',
      'Dirección hidráulica',
      'Cierre centralizado',
      'Alarma',
      'Bluetooth',
      'Computadora de a bordo',
    ],
    specs: {
      engine: '1.6 16v Sigma 110cv',
      steering: 'hydraulic',
      color: 'Gris Mercurio',
      doors: 5,
      wheels: 'Chapa 16 pulgadas',
      wheelSize: '205/55 R16',
      audioSystem: 'Radio con CD + 4 parlantes + Bluetooth',
      headlights: 'halogen',
      sensors: [],
      securityFeatures: [
        'airbags',
        'abs',
      ],
      comfortFeatures: [
        'electric-mirrors',
        'electric-windows',
      ],
    },
  },
  {
    brand: 'Chevrolet',
    model: 'Cruze',
    year: 2019,
    price: 17500000,
    mileage: 72000,
    fuelType: 'nafta',
    transmission: 'automatica',
    status: 'available',
    featured: false,
    description: 'Chevrolet Cruze LT. Muy buen estado general, ideal para uso familiar o viajes. Service al día.',
    features: [
      'Aire acondicionado',
      'Dirección asistida',
      'Cierre centralizado',
      'Alarma',
      'Bluetooth',
      'Control de estabilidad',
    ],
    specs: {
      engine: '1.4 Turbo 153cv',
      steering: 'electric',
      color: 'Negro Carbon',
      doors: 4,
      wheels: 'Aleación 17 pulgadas',
      wheelSize: '225/45 R17',
      audioSystem: 'MyLink 7" + 6 parlantes',
      headlights: 'halogen',
      sensors: ['parking'],
      securityFeatures: [
        'airbags',
        'abs',
        'esp',
        'traction-control',
      ],
      comfortFeatures: [
        'cruise-control',
        'electric-mirrors',
        'electric-windows',
        'climate-control',
      ],
    },
  },
  {
    brand: 'Nissan',
    model: 'Versa',
    year: 2022,
    price: 19500000,
    mileage: 22000,
    fuelType: 'nafta',
    transmission: 'automatica',
    status: 'available',
    featured: false,
    description: 'Nissan Versa Advance. Espacioso y cómodo. Único dueño. Ideal para familia o uso profesional.',
    features: [
      'Aire acondicionado',
      'Dirección asistida',
      'Cierre centralizado',
      'Bluetooth',
      'Sensor de estacionamiento',
    ],
    specs: {
      engine: '1.6 16v 118cv',
      steering: 'electric',
      color: 'Plata Diamante',
      doors: 4,
      wheels: 'Aleación 16 pulgadas',
      wheelSize: '195/55 R16',
      audioSystem: 'Pantalla táctil 7" + 4 parlantes',
      headlights: 'halogen',
      sensors: ['parking'],
      securityFeatures: [
        'airbags',
        'abs',
        'esp',
        'isofix',
      ],
      comfortFeatures: [
        'electric-mirrors',
        'electric-windows',
        'climate-control',
      ],
    },
  },
  {
    brand: 'Renault',
    model: 'Sandero',
    year: 2021,
    price: 16500000,
    mileage: 45000,
    fuelType: 'nafta',
    transmission: 'manual',
    status: 'available',
    featured: false,
    description: 'Renault Sandero Zen. Excelente estado, muy económico. Perfecto para uso urbano.',
    features: [
      'Aire acondicionado',
      'Dirección asistida',
      'Cierre centralizado',
      'Alarma',
      'Bluetooth',
    ],
    specs: {
      engine: '1.6 16v 115cv',
      steering: 'electric',
      color: 'Rojo Intenso',
      doors: 5,
      wheels: 'Chapa 15 pulgadas',
      wheelSize: '185/65 R15',
      audioSystem: 'MediaNav 7" + 4 parlantes + Bluetooth',
      headlights: 'halogen',
      sensors: [],
      securityFeatures: [
        'airbags',
        'abs',
        'esp',
      ],
      comfortFeatures: [
        'electric-mirrors',
        'electric-windows',
      ],
    },
  },
  {
    brand: 'Peugeot',
    model: '308',
    year: 2020,
    price: 21500000,
    mileage: 48000,
    fuelType: 'diesel',
    transmission: 'manual',
    status: 'available',
    featured: false,
    description: 'Peugeot 308 HDi Feline. Motor diesel muy económico, ideal para viajes largos. Excelente autonomía.',
    features: [
      'Climatronic bizona',
      'Control de crucero',
      'Asientos de cuero',
      'Bluetooth',
      'Sensor de estacionamiento',
      'Techo corredizo',
    ],
    specs: {
      engine: '1.6 HDi 115cv Turbo Diesel',
      steering: 'electric',
      color: 'Blanco Banquise',
      doors: 5,
      wheels: 'Aleación 17 pulgadas',
      wheelSize: '225/45 R17',
      audioSystem: 'Pantalla táctil 9.7" + 6 parlantes',
      headlights: 'led',
      sensors: ['parking', 'rain'],
      securityFeatures: [
        'airbags',
        'abs',
        'esp',
        'traction-control',
      ],
      comfortFeatures: [
        'cruise-control',
        'sunroof',
        'leather-seats',
        'heated-seats',
        'electric-mirrors',
        'electric-windows',
        'dual-zone-climate',
      ],
    },
  },
  {
    brand: 'Citroën',
    model: 'C4 Cactus',
    year: 2022,
    price: 23500000,
    mileage: 18000,
    fuelType: 'nafta',
    transmission: 'automatica',
    status: 'reserved',
    featured: true,
    description: 'Citroën C4 Cactus Shine Pack. **RESERVADO** - Consultar disponibilidad. Estado impecable, full equipo.',
    features: [
      'Sistema Grip Control',
      'Asientos Advanced Comfort',
      'Pantalla táctil 10"',
      'Sistema de audio 8 parlantes',
      'Cámara de 360°',
      'Asistente de estacionamiento',
      'Cargador inalámbrico',
      'Airbumps',
    ],
    specs: {
      engine: '1.6 VTi 115cv',
      steering: 'electric',
      color: 'Azul Eléctrico',
      doors: 5,
      wheels: 'Aleación 17 pulgadas',
      wheelSize: '205/55 R17',
      audioSystem: 'Pantalla 10" + Sistema HiFi 8 parlantes',
      headlights: 'led',
      sensors: ['parking', 'reverse', 'blindspot'],
      securityFeatures: [
        'airbags',
        'abs',
        'esp',
        'traction-control',
        'brake-assist',
        'hill-holder',
        'isofix',
      ],
      comfortFeatures: [
        'cruise-control',
        'leather-seats',
        'electric-mirrors',
        'electric-windows',
        'climate-control',
        'dual-zone-climate',
        'start-stop',
        'parking-brake-electric',
      ],
    },
  },
  {
    brand: 'Fiat',
    model: 'Cronos',
    year: 2022,
    price: 20500000,
    mileage: 35000,
    fuelType: 'nafta',
    transmission: 'automatica',
    status: 'sold',
    featured: false,
    description: 'Fiat Cronos Drive. **VENDIDO** - Pregunte por similares. Excelente estado, único dueño, service oficial.',
    features: [
      'Aire acondicionado',
      'Dirección asistida',
      'Cierre centralizado',
      'Alarma',
      'Bluetooth',
      'Sensor de estacionamiento',
    ],
    specs: {
      engine: '1.3 Firefly 99cv',
      steering: 'electric',
      color: 'Gris Colosseo',
      doors: 4,
      wheels: 'Aleación 16 pulgadas',
      wheelSize: '195/55 R16',
      audioSystem: 'Uconnect 7" + 6 parlantes',
      headlights: 'halogen',
      sensors: ['parking'],
      securityFeatures: [
        'airbags',
        'abs',
        'esp',
        'isofix',
      ],
      comfortFeatures: [
        'electric-mirrors',
        'electric-windows',
        'climate-control',
      ],
    },
  },
];

async function seed() {
  console.log('🌱 Iniciando seed con nuevo esquema completo...\n');

  // Clear existing cars
  console.log('🗑️  Eliminando autos existentes...');
  await prisma.car.deleteMany({});
  console.log('✅ Autos eliminados\n');

  console.log('🚗 Creando autos de ejemplo con especificaciones completas...\n');

  for (const carData of sampleCars) {
    const car = await prisma.car.create({
      data: {
        brand: carData.brand,
        model: carData.model,
        year: carData.year,
        price: carData.price,
        mileage: carData.mileage,
        fuelType: carData.fuelType as any,
        transmission: carData.transmission as any,
        status: carData.status as any,
        featured: carData.featured,
        description: carData.description,
        features: carData.features,
        specs: carData.specs,
      },
    });

    console.log(`✅ ${car.brand} ${car.model} (${car.year})`);
    console.log(`   💰 $${Number(car.price).toLocaleString('es-AR')}`);
    console.log(`   🎨 ${carData.specs.color}`);
    console.log(`   ⚙️  ${carData.specs.engine}`);
    console.log(`   📋 ${carData.features.length} características`);
    console.log();
  }

  console.log('✨ Seed completado exitosamente!');
  console.log(`📊 Total de autos creados: ${sampleCars.length}`);
  console.log('\n🔥 Destacados:');
  sampleCars.filter(c => c.featured).forEach(c => {
    console.log(`   ⭐ ${c.brand} ${c.model}`);
  });
  console.log('\n📌 Estados:');
  console.log(`   Disponibles: ${sampleCars.filter(c => c.status === 'available').length}`);
  console.log(`   Vendidos: ${sampleCars.filter(c => c.status === 'sold').length}`);
  console.log(`   Reservados: ${sampleCars.filter(c => c.status === 'reserved').length}`);

  await prisma.$disconnect();
}

seed().catch((error) => {
  console.error('❌ Error durante el seed:', error);
  process.exit(1);
});
